const express = require('express')
const app = express()
const path = require('path')
const cors = require('cors')
const upload = require('express-fileupload')
const mongoose = require('mongoose')
require('dotenv').config()
mongoose.connect('mongodb://0.0.0.0:27017/rade')
.then(()=> console.log('connected')).catch(e=>console.log('err',e.message))
app.use("/public/assets",express.static(__dirname))
app.use(cors({origin:"*"}))
app.use(express.json())
app.use(express.urlencoded({extended:false}))
app.use(upload({limits:20*1024*1024}))
const userRoute = require('./user/routes')
const adminRoute = require('./user/admin/routes')
app.use(adminRoute)
app.use(userRoute)

app.listen(2300,'10.14.30.240',(e)=>console.log('listening'))